{"uid":"db984a2e1cea44ae","name":"test_trigonometry_operations[asin(0.5)-0.5235987755982988]","fullName":"tests.test_simple_operations#test_trigonometry_operations","historyId":"926c9b8be679a415e3c023c412601a13","time":{"start":1693154881026,"stop":1693154881027,"duration":1},"description":"\nВ рамках этих тест-кейсов разные машины могут давать разный результат.\nПричина в разных способах округления чисел с плавающей точкой.\n","descriptionHtml":"<p>В рамках этих тест-кейсов разные машины могут давать разный результат.<br />\nПричина в разных способах округления чисел с плавающей точкой.</p>\n","status":"skipped","statusMessage":"XFAIL expecting failure\n\nAssertionError: assert 0.5235987755982989 == 0.5235987755982988\n +  where 0.5235987755982989 = <bound method CalculatorModel.calculate_expression of <smartcalc.model.model.CalculatorModel object at 0x0000016739837290>>('asin(0.5)')\n +    where <bound method CalculatorModel.calculate_expression of <smartcalc.model.model.CalculatorModel object at 0x0000016739837290>> = <smartcalc.model.model.CalculatorModel object at 0x0000016739837290>.calculate_expression","statusTrace":"expression = 'asin(0.5)', expected_result = 0.5235987755982988\n\n    @allure.description(\"\"\"\n    В рамках этих тест-кейсов разные машины могут давать разный результат.\n    Причина в разных способах округления чисел с плавающей точкой.\n    \"\"\")\n    @pytest.mark.xfail(condition=lambda: True, reason='expecting failure')\n    @pytest.mark.parametrize(\"expression, expected_result\",\n                             [(\"log(10) + log(10)\", 4.605170185988092),\n                              (\"sin(4)\", -0.7568024953079282),\n                              (\"cos(8)\", -0.14550003380861354),\n                              (\"tan(5)\", -3.380515006246585),\n                              (\"asin(0.5)\", 0.5235987755982988),\n                              (\"acos(0.8)\", 0.6435011087932843),\n                              (\"atan(0.9)\", 0.7328151017865067)])\n    def test_trigonometry_operations(expression, expected_result):\n>       assert calc_model.calculate_expression(expression) == expected_result\nE       AssertionError: assert 0.5235987755982989 == 0.5235987755982988\nE        +  where 0.5235987755982989 = <bound method CalculatorModel.calculate_expression of <smartcalc.model.model.CalculatorModel object at 0x0000016739837290>>('asin(0.5)')\nE        +    where <bound method CalculatorModel.calculate_expression of <smartcalc.model.model.CalculatorModel object at 0x0000016739837290>> = <smartcalc.model.model.CalculatorModel object at 0x0000016739837290>.calculate_expression\n\ntest_simple_operations.py:46: AssertionError","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"tag","value":"@pytest.mark.xfail(condition=<function <lambda> at 0x0000016739831800>, reason='expecting failure')"},{"name":"parentSuite","value":"tests"},{"name":"suite","value":"test_simple_operations"},{"name":"host","value":"AndrewLaptop"},{"name":"thread","value":"5916-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.test_simple_operations"},{"name":"resultFormat","value":"allure2"}],"parameters":[{"name":"expected_result","value":"0.5235987755982988"},{"name":"expression","value":"'asin(0.5)'"}],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[],"tags":["@pytest.mark.xfail(condition=<function <lambda> at 0x0000016739831800>, reason='expecting failure')"]},"source":"db984a2e1cea44ae.json","parameterValues":["0.5235987755982988","'asin(0.5)'"]}